[mymega]
type = mega
user = nzriamirmhmd54@gmail.com
pass = tWe56Yszjk7DMcQ9RrUqHWx1Q3w4h0qFvbxFng

[acc_2]
type = mega
user = w413121w@gmail.com
pass = rs7u6k28jhYDxMhNfHK3DD5cSGwE10keeX-wiA

[acc_3]
type = mega
user = w413121w@gmail.com
pass = B3Kh5j0-tWFd6kKzYYYn7JyEU2-2tDuyQdYiFu-5GA

[acc_13]
type = mega
user = nzriamirmhmd54@gmail.com
pass = fU0kBcVXTlWJXxKr9NwQygg79m_sQIHl5yejwQ

[u5927935256_1]
type = mega
user = nzriamirmhmd54@gmail.com
pass = u9vWwOKLIe6Isv8pZ8xQrv7V45F7ztt1z0_L3w
