[mymega]
type = mega
user = nzriamirmhmd54@gmail.com
pass = tWe56Yszjk7DMcQ9RrUqHWx1Q3w4h0qFvbxFng
session_id = j42IHZ3f6yfkmEEQNnPR71NWUW1yeGdfRmxvswV5Fb4RBdK9cQ0lQ8DoOA
master_key = Px7soQgye5JickiNcGKo8A==

[acc_2]
type = mega
pass = rs7u6k28jhYDxMhNfHK3DD5cSGwE10keeX-wiA
user = w413121w@gmail.com

[acc_3]
type = mega
user = w413121w@gmail.com
pass = B3Kh5j0-tWFd6kKzYYYn7JyEU2-2tDuyQdYiFu-5GA
session_id = BnpbMZAnrbhxqqzkS1Mkx19BSjNhV01YQmZJyjj49yB4u0FwA0jwnZlRfA
master_key = tKCqn1nTSx6X0iQVlqxBww==

[acc_13]
type = mega
user = nzriamirmhmd54@gmail.com
pass = fU0kBcVXTlWJXxKr9NwQygg79m_sQIHl5yejwQ
session_id = j42IHZ3f6yfkmEEQNnPR71NWUW1yeGdfRmxvswV5Fb4RBdK9cQ0lQ8DoOA
master_key = Px7soQgye5JickiNcGKo8A==

[u5927935256_1]
type = mega
user = nzriamirmhmd54@gmail.com
pass = u9vWwOKLIe6Isv8pZ8xQrv7V45F7ztt1z0_L3w
session_id = j42IHZ3f6yfkmEEQNnPR71NWUW1yeGdfRmxvswV5Fb4RBdK9cQ0lQ8DoOA
master_key = Px7soQgye5JickiNcGKo8A==

